<h2><center>Week 3 - Assignment</center></h2>
<h3><center>Programming for Data Science 2024</center></h3>

Exercises for the topics covered in the third lecture.

The exercise will be marked as passed if you get **at least 10/15** points.

Exercises must be handed in via **ILIAS** (Homework assignments). Deliver your submission as a compressed file (zip) containing one .py or .ipynb file with all exercises. The name of both the .zip and the .py/.ipynb file must be *SurnameName* of the two members of the group. Example: Riccardo Cusinato + Athina Tzovara = *CusinatoRiccardo_TzovaraAthina.zip* .

It's important to use comments to explain your code and show that you're able to take ownership of the exercises and discuss them.

You are not expected to collaborate outside of the group on exercises and submitting other groups’ code as your own will result in 0 points.

For questions contact: *riccardo.cusinato@unibe.ch* with the subject: *Programming for Data Science 2024*.

**Deadline: 14:00, March 14, 2024.**

<h3 style="text-align:left;">Exercise 1 - Error investigation<span style="float: right">2 points</span></h3>

The code below squares and sums the numbers in the array *arr*, and holds the result in the variable *squared_sum*, which should be 1135. However, that is not the case. Correct the code and explain in a comment , clearly and amply, what was wrong.

In [25]:
import numpy as np

arr = np.array([13, 14, 15, 16, 17], dtype=np.int16)
squared_sum = np.sum(arr ** 2)
squared_sum

[169 196 225 256 289]


1135

In [26]:
# The problem is that numpy.int8 (signed int) ranges from -128 to 127 but all the squares from
# the array are larger than a signed 8 bit int can represent. uint8 would be sufficient for 13, 14 and 15, but 16^2 is the same as 2^8 which is 1 digit bigger than uint8 can store (because 0 has to be included).
# so the solution is to make it at least 16 bits long (int or uint works both)


<h3 style="text-align:left;">Exercise 2 - Vacation selector<span style="float: right">3 points</span></h3>

The code below defines five vacation destinations (*locations*) and four attributes for each (*attributes*). Each row describes one destination, and the columns represent scores on the factors scenery, activities, food, and nightlife.

Write a function *vacation_advisor* that asks the user whether they find each of the attributes important or not, and suggests the best vacation spot based on these preferences.

Use techniques from the third lecture to solve the exercise.

Example interaction:
```python
Is scenery important to you [y/n]?    > y
Is activities important to you [y/n]? > y
Is food important to you [y/n]?       > n
Is nightlife important to you [y/n]?  > n
Based on your preferences, the best destination is Australia
```

In [78]:
# List of destinations
locations = np.array([ "Hawaii", "Thailand", "Italy", "Australia", "Japan" ])

# List of attributes for each destination. Each column is an attribute. Each row a destination.
attributes = np.array([
    [8, 8, 7, 6],
    [7, 9, 8, 7],
    [8, 6, 9, 7],
    [9, 8, 8, 6],
    [7, 9, 7, 8]
])

# Declare attribute names and initialize boolean array with preferences
attribute_names = ['scenery', 'activities', 'food', 'nightlife']


In [86]:
def get_input(attribute: str) -> int:
    print(f"Is {attribute} important to you [y/n]?")
    important: str = handle_input()           
    return 1 if important == 'y' else 0


def handle_input() -> str:
    while True:
         result: str = input("")
         if result == 'y' or result == 'n':
              return result
         print("Please answer \"y\" for yes and \"n\" for no")


while True:
    attribute_importance: np.array = np.array([get_input("scenery"), get_input("activities"), get_input("food"), get_input("nightlife")])
    importance_of_attributes: np.array= attribute_importance * attributes[:, np.newaxis]
    max_index: int = np.argmax( np.sum(importance_of_attributes, axis = 2))

    print(f"Based on your preferences, the best destination is {locations[max_index]}")
    
    print("------------------------------------\nWould you like to change preferences?")
    if handle_input() == 'n':
        break

Is scenery important to you [y/n]?
Is activities important to you [y/n]?
Is food important to you [y/n]?
Is nightlife important to you [y/n]?
Based on your preferences, the best destination is Italy
------------------------------------
Would you like to change preferences?


<h3 style="text-align:left;">Exercise 3 - Indexing<span style="float: right">3 points</span></h3>

You have two arrays of the same length: temperature *temp*, and humidity, *rh*. Write a program that:
1) Substitutes the values of *temp* for which the corresponding values of *rh* is less than 0.3 with *np.nan*.
2) On this new temperature array, calculate the mean value (do **not** calculate it on the original array).

As an example:

```python
temp = [70, 80, 90]
rh = [0.5, 0.2, 0.6]

temp_nan --> [70, np.nan, 90]
temp_avg --> 80
```

In [87]:
# Generate some surrogate data

np.random.seed(29041996)  # Make sure we all have the same data
temp = 20 * np.cos(np.linspace(0, 2 * np.pi, 100)) + 80 + 2 * np.random.randn(100)
rh = np.abs(0.1 * np.cos(np.linspace(0, 4 * np.pi, 100)) 
            + 0.3 + 0.05 * np.random.randn(100))

In [93]:
print(f"temp_nan --> {np.where(rh < 0.3, np.nan, rh)}")
print(f"temp_avg --> {np.mean(temp):.2f}")

temp_nan --> [0.37649075 0.41857708 0.41553862 0.35028076 0.40030482 0.32611461
 0.33361994        nan 0.37445786 0.44330325        nan 0.34688538
        nan        nan        nan 0.30858741 0.31015845        nan
        nan        nan 0.30991538        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan 0.31119358 0.35520544
 0.32894799 0.30334288 0.3727636  0.32481739        nan        nan
 0.35235689 0.4015986  0.43445632 0.3398031  0.38966828 0.43772596
 0.47284863 0.39973687 0.38113616 0.3964504  0.34324162 0.42071724
 0.36577697 0.35257995 0.37101488 0.35909791        nan 0.34605456
 0.43186955 0.33807326 0.31587005 0.34303918 0.31680012        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan 0.32769864 0.30461726        nan        nan        nan
        nan        nan 0.35382345 0.32424633 0.38

<h3 style="text-align:left;">Exercise 4 - Base converter<span style="float: right">2 points</span></h3>

Write a function *int_to_bin* that takes a positive integer as input and returns the binary equivalent of that integer.

You can **not** use built-in methods such as *bin()* in your solution.

In [125]:
import math

def int_to_bin(number: int) -> int:
    highest_bit: int= math.floor(math.log2(number))
    result: str = ""
    for power in range(highest_bit, -1, -1):
        if 2 ** power > number:
            result += '0'
        else:
            number-= 2 ** power
            result += '1'
    return int(result)


number = 257
print(f"{number = }\npython implementation: {bin(number) = }\nown implementation {int_to_bin(number) = }")

number = 257
python implementation: bin(number) = '0b100000001'
own implementation int_to_bin(number) = 100000001


<h3 style="text-align:left;">Exercise 5 - Broadcasting<span style="float: right">2 points</span></h3>

Reshape *a* so it is possible to multiply *a* and *b*, and explain why you had to reshape *a* to be able to multiply the two arrays.

In [131]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([2, 3])

In [134]:
# To multiply a with b the number of columns have to match the number of rows of b. If we transpose the matrix we get that:
a_transpose = a.T

print(a,a_transpose,a_transpose*b, sep="\n -> \n")

[[1 2 3]
 [4 5 6]]
 -> 
[[1 4]
 [2 5]
 [3 6]]
 -> 
[[ 2 12]
 [ 4 15]
 [ 6 18]]


<h3 style="text-align:left;">Exercise 6 - Moving average<span style="float: right">3 points</span></h3>

Given the array of values *a*, we can calculate the moving average by averaging nearby values and repeating the procedure sliding along the array. Here's an example of a 3-point moving average (ignoring the edges), with a for loop:

In [146]:
np.random.seed(29041996)
a = np.round(30 + np.random.randn(20) * 2, 1)
print(a)

# Moving average
a_avg = np.zeros_like(a)
# We're just ignoring the edge effects here
for i in range(1, len(a) - 1):
    sub = a[i - 1:i + 2]
    a_avg[i] = sub.mean()
# For the first and last point, we use the original values.
a_avg[[0, -1]] = a[[0, -1]]
print(a_avg)

[27.6 28.3 30.2 29.1 29.  31.8 31.9 30.5 29.9 32.5 31.1 29.4 31.6 29.8
 30.  27.6 28.9 29.9 28.5 30.5]
[27.6        28.7        29.2        29.43333333 29.96666667 30.9
 31.4        30.76666667 30.96666667 31.16666667 31.         30.7
 30.26666667 30.46666667 29.13333333 28.83333333 28.8        29.1
 29.63333333 30.5       ]


Write a function *mov_avg* that takes an array in input and returns its 3-point moving average. You **have to use broadcasting** to compute the moving average. As in the example, use the original array values at the borders.

In [145]:
def mov_avg(arr):
    """
    Calculates the 3-point moving average of an array using broadcasting.

    Args:
        arr (numpy.ndarray): Input array.

    Returns:
        numpy.ndarray: Array with the 3-point moving average.
    """
    # Create a rolling window of size 3
    rolling_window = np.lib.stride_tricks.sliding_window_view(arr, window_shape=3)

    # Calculate the mean along the last axis (axis=-1)
    moving_average = np.mean(rolling_window, axis=-1)

    # Use the original array values at the borders
    moving_average[[0, -1]] = arr[[0, -1]]

    return moving_average

print("Original array:")
print(a)

a_avg = mov_avg(a)
print("\n3-point moving average:")
print(a_avg)

Original array:
[27.6 28.3 30.2 29.1 29.  31.8 31.9 30.5 29.9 32.5 31.1 29.4 31.6 29.8
 30.  27.6 28.9 29.9 28.5 30.5]

3-point moving average:
[27.6        29.2        29.43333333 29.96666667 30.9        31.4
 30.76666667 30.96666667 31.16666667 31.         30.7        30.26666667
 30.46666667 29.13333333 28.83333333 28.8        29.1        30.5       ]
