<h2><center>Week 3 - Assignment</center></h2>
<h3><center>Programming for Data Science 2024</center></h3>

Exercises for the topics covered in the third lecture.

The exercise will be marked as passed if you get **at least 10/15** points.

Exercises must be handed in via **ILIAS** (Homework assignments). Deliver your submission as a compressed file (zip) containing one .py or .ipynb file with all exercises. The name of both the .zip and the .py/.ipynb file must be *SurnameName* of the two members of the group. Example: Riccardo Cusinato + Athina Tzovara = *CusinatoRiccardo_TzovaraAthina.zip* .

It's important to use comments to explain your code and show that you're able to take ownership of the exercises and discuss them.

You are not expected to collaborate outside of the group on exercises and submitting other groups’ code as your own will result in 0 points.

For questions contact: *riccardo.cusinato@unibe.ch* with the subject: *Programming for Data Science 2024*.

**Deadline: 14:00, March 14, 2024.**

<h3 style="text-align:left;">Exercise 1 - Error investigation<span style="float: right">2 points</span></h3>

The code below squares and sums the numbers in the array *arr*, and holds the result in the variable *squared_sum*, which should be 1135. However, that is not the case. Correct the code and explain in a comment , clearly and amply, what was wrong.

In [3]:
import numpy as np

arr = np.array([13, 14, 15, 16, 17], dtype=np.int16)
squared_sum = np.sum(arr ** 2)
squared_sum

1135

In [4]:
# The problem is that numpy.int8 (signed int) ranges from -128 to 127 but all the squares from
# the array are larger than a signed 8 bit int can represent. uint8 would be sufficient for 13, 
# 14 and 15, but 16^2 is the same as 2^8 which is 1 digit bigger than uint8 can store.
# so the solution is to make it at least 16 bits long (int or uint both work)


<h3 style="text-align:left;">Exercise 2 - Vacation selector<span style="float: right">3 points</span></h3>

The code below defines five vacation destinations (*locations*) and four attributes for each (*attributes*). Each row describes one destination, and the columns represent scores on the factors scenery, activities, food, and nightlife.

Write a function *vacation_advisor* that asks the user whether they find each of the attributes important or not, and suggests the best vacation spot based on these preferences.

Use techniques from the third lecture to solve the exercise.

Example interaction:
```python
Is scenery important to you [y/n]?    > y
Is activities important to you [y/n]? > y
Is food important to you [y/n]?       > n
Is nightlife important to you [y/n]?  > n
Based on your preferences, the best destination is Australia
```

In [5]:
# List of destinations
locations = np.array([ "Hawaii", "Thailand", "Italy", "Australia", "Japan" ])

# List of attributes for each destination. Each column is an attribute. Each row a destination.
attributes = np.array([
    [8, 8, 7, 6],
    [7, 9, 8, 7],
    [8, 6, 9, 7],
    [9, 8, 8, 6],
    [7, 9, 7, 8]
])

# Declare attribute names and initialize boolean array with preferences
attribute_names = ['scenery', 'activities', 'food', 'nightlife']


In [6]:
def get_input(attribute: str) -> int:
    print(f"Is {attribute} important to you [y/n]?")
    important: str = handle_input()           
    return 1 if important == 'y' else 0


def handle_input() -> str:
    while True:
         result: str = input("")
         if result == 'y' or result == 'n':
              return result
         print("Please answer \"y\" for yes and \"n\" for no")


while True:
    attribute_importance: np.array = np.array([get_input("scenery"), get_input("activities"), get_input("food"), get_input("nightlife")])
    importance_of_attributes: np.array = attribute_importance * attributes[:, np.newaxis]
    max_index: int = np.argmax( np.sum(importance_of_attributes, axis = 2))

    print(f"Based on your preferences, the best destination is {locations[max_index]}")
    
    print("------------------------------------\nWould you like to change preferences?")
    if handle_input() == 'n':
        break

Is scenery important to you [y/n]?
Is activities important to you [y/n]?
Is food important to you [y/n]?
Is nightlife important to you [y/n]?
Based on your preferences, the best destination is Hawaii
------------------------------------
Would you like to change preferences?


<h3 style="text-align:left;">Exercise 3 - Indexing<span style="float: right">3 points</span></h3>

You have two arrays of the same length: temperature *temp*, and humidity, *rh*. Write a program that:
1) Substitutes the values of *temp* for which the corresponding values of *rh* is less than 0.3 with *np.nan*.
2) On this new temperature array, calculate the mean value (do **not** calculate it on the original array).

As an example:

```python
temp = [70, 80, 90]
rh = [0.5, 0.2, 0.6]

temp_nan --> [70, np.nan, 90]
temp_avg --> 80
```

In [7]:
# Generate some surrogate data

np.random.seed(29041996)  # Make sure we all have the same data
temp = 20 * np.cos(np.linspace(0, 2 * np.pi, 100)) + 80 + 2 * np.random.randn(100)
rh = np.abs(0.1 * np.cos(np.linspace(0, 4 * np.pi, 100)) 
            + 0.3 + 0.05 * np.random.randn(100))

In [18]:
# replacing the values of temp with nan where the values of rh are less than 0.3
temp_nan= np.where(rh<0.3, np.nan, temp)
# np.nanmean ignores nan values for calulcating the mean
print(f"The new modified temp is {temp_nan}")
print(f"The mean temperature is { np.nanmean(temp_nan):.2f}")

The new modified temp is [ 97.61100965  98.29758553 100.01692772  98.73758771  98.38710799
 100.80608254 100.42365343          nan  97.34895106  99.28378744
          nan  94.70357922          nan          nan          nan
  89.2217891   89.41943969          nan          nan          nan
  81.47344699          nan          nan          nan          nan
          nan          nan          nan          nan          nan
          nan          nan          nan          nan  68.73828046
  67.47413002  68.54133082  65.53398191  64.56197892  64.19909813
          nan          nan  59.92352112  63.86983538  61.88582567
  59.71619218  59.84554475  60.32812302  59.09837842  60.02298563
  58.56227652  58.99225298  57.80804413  61.99996728  61.91705067
  60.34955294  62.5543744   62.38104106          nan  63.96025183
  64.60977283  66.26614781  65.304059    68.41834429  65.57144047
          nan          nan          nan          nan          nan
          nan          nan          nan          na

<h3 style="text-align:left;">Exercise 4 - Base converter<span style="float: right">2 points</span></h3>

Write a function *int_to_bin* that takes a positive integer as input and returns the binary equivalent of that integer.

You can **not** use built-in methods such as *bin()* in your solution.

In [19]:
import math

def int_to_bin(number: int) -> int:
    highest_bit: int= math.floor(math.log2(number))
    result: str = ""
    for power in range(highest_bit, -1, -1):
        if 2 ** power > number:
            result += '0'
        else:
            number-= 2 ** power
            result += '1'
    return int(result)


number = 257
print(f"{number = }\npython implementation:  {bin(number) = }\nown implementation: {int_to_bin(number) = }")

number = 257
python implementation:  bin(number) = '0b100000001'
own implementation: int_to_bin(number) = 100000001


<h3 style="text-align:left;">Exercise 5 - Broadcasting<span style="float: right">2 points</span></h3>

Reshape *a* so it is possible to multiply *a* and *b*, and explain why you had to reshape *a* to be able to multiply the two arrays.

In [10]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([2, 3])

In [11]:
# To multiply a with b the number of columns have to match the number of rows of b. If we transpose the matrix we get that:
a_transpose = a.T

print(a,a_transpose,a_transpose*b, sep="\n -> \n")

[[1 2 3]
 [4 5 6]]
 -> 
[[1 4]
 [2 5]
 [3 6]]
 -> 
[[ 2 12]
 [ 4 15]
 [ 6 18]]


<h3 style="text-align:left;">Exercise 6 - Moving average<span style="float: right">3 points</span></h3>

Given the array of values *a*, we can calculate the moving average by averaging nearby values and repeating the procedure sliding along the array. Here's an example of a 3-point moving average (ignoring the edges), with a for loop:

In [12]:
np.random.seed(29041996)
a = np.round(30 + np.random.randn(20) * 2, 1)
print(a)

# Moving average
a_avg = np.zeros_like(a)
# We're just ignoring the edge effects here
for i in range(1, len(a) - 1):
    sub = a[i - 1:i + 2]
    a_avg[i] = sub.mean()
# For the first and last point, we use the original values.
a_avg[[0, -1]] = a[[0, -1]]
print(a_avg)

[27.6 28.3 30.2 29.1 29.  31.8 31.9 30.5 29.9 32.5 31.1 29.4 31.6 29.8
 30.  27.6 28.9 29.9 28.5 30.5]
[27.6        28.7        29.2        29.43333333 29.96666667 30.9
 31.4        30.76666667 30.96666667 31.16666667 31.         30.7
 30.26666667 30.46666667 29.13333333 28.83333333 28.8        29.1
 29.63333333 30.5       ]


Write a function *mov_avg* that takes an array in input and returns its 3-point moving average. You **have to use broadcasting** to compute the moving average. As in the example, use the original array values at the borders.

In [20]:
def mov_avg(a):
    a_avg= np.zeros_like(a)
    # Creating three windows to add three consecutive elements in a
    sub=a[:-2]+a[1:-1]+a[2:]
    # Assigning the average of the three consecutive elements to the corresponding position in a_avg. Note that the first and last elements are excluded.
    a_avg[1:-1]= sub/3
    # For the first and last element, we use the original values.
    a_avg[[0, -1]] = a[[0, -1]]
    return a_avg

# Testing the function
print("Original array:")
print(a)
print("\n3-point moving average:")
print(mov_avg(a))

Original array:
[27.6 28.3 30.2 29.1 29.  31.8 31.9 30.5 29.9 32.5 31.1 29.4 31.6 29.8
 30.  27.6 28.9 29.9 28.5 30.5]

3-point moving average:
[27.6        28.7        29.2        29.43333333 29.96666667 30.9
 31.4        30.76666667 30.96666667 31.16666667 31.         30.7
 30.26666667 30.46666667 29.13333333 28.83333333 28.8        29.1
 29.63333333 30.5       ]
