<h2><center>Week 4 - Assignment - Solutions</center></h2>
<h3><center>Programming for Data Science 2024</center></h3>

Exercises for the topics covered in the fourth lecture.

The exercise will be marked as passed if you get **at least 10/15** points.

Exercises must be handed in via **ILIAS** (Homework assignments). Deliver your submission as a compressed file (zip) containing one .py or .ipynb file with all exercises. The name of both the .zip and the .py/.ipynb file **must** be *SurnameName* of the two members of the group. Example: Riccardo Cusinato + Athina Tzovara = *CusinatoRiccardo_TzovaraAthina.zip* .

It's important to use comments to explain your code and show that you're able to take ownership of the exercises and discuss them.

You are not expected to collaborate outside of the group on exercises and submitting other groups’ code as your own will result in 0 points.

For questions contact: *riccardo.cusinato@unibe.ch* with the subject: *Programming for Data Science 2024*.

**Deadline: 14:00, March 21, 2024.**

<h3 style="text-align:left;">Exercise 1 - Create Dataframes<span style="float: right">5 points</span></h3>

Create a DataFrame *episodes_df* with the columns **ses**, **ep**, and **title**, as below:

|**ses**|**ep**|**title**|
|:---|:---|:---|
|1|1|One|
|1|2|Two|
|2|1|Three|
|2|2|Four|

Create a DataFrame *imdb_df* with the columns **ses**, **ep**, and **score**, as below:

|**ses**|**ep**|**score**|
|:---|:---|:---|
|1|1|8.4|
|1|2|8.1|
|2|1|7.9|
|2|2|7.7|

Merge the two DataFrames. Then, find and print the title of the episode with the higest score.

**NB**: To merge the two dataframes you have to use the **merge** method:
```python
merged_df = episodes_df.merge(imdb_df, on=['ses', 'ep'])
```


1. By manipulating the dataframes, find and print the title of the episode with the higest score. (*3 points*)

In [2]:
import pandas as pd

episodes_df = pd.DataFrame({
    'ses': [1, 1, 2, 2],
    'ep': [1, 2, 1, 2],
    'title': ['One', 'Two', 'Three', 'Four']
})

imdb_df = pd.DataFrame({
    'ses': [1, 1, 2, 2],
    'ep': [1, 2, 1, 2],
    'score': [8.5, 7.9, 9.1, 8.8]
})

merged_df = episodes_df.merge(imdb_df, on=['ses', 'ep'])

print(merged_df)
print("Title with highest score:", merged_df["title"].iloc[merged_df["score"].idxmax()])


   ses  ep  title  score
0    1   1    One    8.5
1    1   2    Two    7.9
2    2   1  Three    9.1
3    2   2   Four    8.8
Title with highest score: Three


2. Change the **score** of the entry with the title "Three" in the DataFrame you created in Task 1. The new score should be 6. (*2 points*)

In [3]:
merged_df.loc[merged_df['title'] == 'Three', ['score']] = 6

merged_df

ses  ep  title  score
0    1   1    One    8.5
1    1   2    Two    7.9
2    2   1  Three    6.0
3    2   2   Four    8.8

<h3 style="text-align:left;">Exercise 2 - Load DataFrames<span style="float: right">6 points</span></h3>

1. Load the two CSV files 'silicon_valley_episodes.csv' and 'silicon_valley_imdb.csv', found in the "data" directory, as DataFrames. Merge the two DataFrames as in the first task, using **season** and **episode_num** as keys to merge on. (*2 points*)
```python
episodes_df = pd.read_csv('./data/silicon_valley_episodes.csv')
imdb_df = pd.read_csv('./data/silicon_valley_imdb.csv')
```

In [17]:
import pandas as pd
import numpy as np

episodes_df = pd.read_csv('./data/silicon_valley_episodes.csv')
imdb_df = pd.read_csv('./data/silicon_valley_imdb.csv')

merged_df = episodes_df.merge(imdb_df, on=['season', 'episode_num'])

print("Episodes dataframe:")
print(episodes_df.columns)
print("IMDB dataframe:")
print(imdb_df.columns)
print("Common columns to both dataframes:", np.intersect1d(episodes_df.columns, imdb_df.columns))
print("Merged dataframe: ")
merged_df.head()

Episodes dataframe:
Index(['season', 'episode_num', 'episode_num_overall', 'title', 'directed_by',
       'written_by', 'original_air_date', 'us_viewers'],
      dtype='object')
IMDB dataframe:
Index(['season', 'episode_num', 'title', 'original_air_date', 'imdb_rating',
       'total_votes', 'desc'],
      dtype='object')
Common columns to both dataframes: ['episode_num' 'original_air_date' 'season' 'title']
Merged dataframe: 


season  episode_num  episode_num_overall                    title_x  \
0       1            1                    1     Minimum Viable Product   
1       1            2                    2              The Cap Table   
2       1            3                    3  Articles of Incorporation   
3       1            4                    4           Fiduciary Duties   
4       1            5                    5             Signaling Risk   

    directed_by                                   written_by  \
0    Mike Judge  Mike Judge & John Altschuler & Dave Krinsky   
1    Mike Judge                                  Carson Mell   
2  Tricia Brock              Matteo Borghese & Rob Turbovsky   
3  Maggie Carey                                   Ron Weiner   
4     Alec Berg                                  Jessica Gao   

  original_air_date_x  us_viewers                    title_y  \
0            06.04.14     1980000     Minimum Viable Product   
1            13.04.14     1690000              The Cap Table   
2            20.04.14     1620000  Articles of Incorporation   
3            27.04.14     1550000           Fiduciary Duties   
4            04.05.14     1820000             Signaling Risk   

  original_air_date_y  imdb_rating  total_votes  \
0         6 Apr. 2014          7.7         2685   
1        13 Apr. 2014          7.8         2163   
2        20 Apr. 2014          8.0         2083   
3        27 Apr. 2014          7.7         1931   
4          4 May 2014          8.3         1980   

                                                desc  
0  Richard is a computer programmer. He has to ch...  
1  Richard hires Jared to design a business plan....  
2  The guys find themselves in trouble with their...  
3  Richard drunkenly promises to make Erlich a bo...  
4  Now that Pied Piper is the official company na...

2. Create a new DataFrame, called **df_best**, containing only the episodes with an **imdb_rating** at or above 9. Use the DataFrame created in the previous task as a starting point. (*2 points*)

In [8]:
df_best = merged_df[merged_df['imdb_rating'] >= 9]
df_best

season  episode_num  episode_num_overall                        title_x  \
7        1            8                    8  Optimal Tip-To-Tip Efficiency   
17       2           10                   18         Two Days of the Condor   
45       5            8                   46              Fifty-One Percent   

   directed_by written_by original_air_date_x  us_viewers  \
7   Mike Judge  Alec Berg            01.06.14     1740000   
17   Alec Berg  Alec Berg            14.06.15     2110000   
45   Alec Berg  Alec Berg            13.05.18      707000   

                          title_y original_air_date_y  imdb_rating  \
7   Optimal Tip-To-Tip Efficiency         1 Jun. 2014          9.3   
17         Two Days of the Condor        14 Jun. 2015          9.2   
45              Fifty-One Percent         13 May 2018          9.1   

    total_votes                                               desc  
7          3627  Pied Piper makes it to the next stage of Disru...  
17         2320  The verdict on Pied Piper's fate coincides wit...  
45         2128  PiperNet launches, but an early success makes ...

3. Find mean number of **us_viewers** for episodes with an IMDB score greater than or equal to 9, and for episodes with an IMDB score lower than 9, and print the means. (*2 points*)

In [9]:
# . is equivalent to [""]

print(merged_df[merged_df['imdb_rating'] >= 9]["us_viewers"].mean())
print(merged_df[merged_df['imdb_rating'] < 9].us_viewers.mean())

1519000.0
1234000.0


<h3 style="text-align:left;">Exercise 3 - DataFrames Ufuncs<span style="float: right">4 points</span></h3>

Create the two dataframe *df1* and *df2* with the following code:

In [3]:
import numpy as np
import pandas as pd

df1 = pd.DataFrame(
    np.arange(1, 10).reshape(3, 3),
    columns=["a", "b", "c"],
    index=["1", "2", "3"]
)

df2 = pd.DataFrame(
    np.arange(1, 10).reshape(3, 3) / 2,
    columns=["a", "b", "d"],
    index=["1", "2", "4"]
)

In [4]:
df1

a  b  c
1  1  2  3
2  4  5  6
3  7  8  9

In [5]:
df2

a    b    d
1  0.5  1.0  1.5
2  2.0  2.5  3.0
4  3.5  4.0  4.5

1. Add the two dataframes together, with the appropriate pandas method, and print the result. (*0.5 points*)

In [12]:
df1.add(df2)

a    b   c   d
1  1.5  3.0 NaN NaN
2  6.0  7.5 NaN NaN
3  NaN  NaN NaN NaN
4  NaN  NaN NaN NaN

In [7]:
pd.concat([df1, df2])

a    b    c    d
1  1.0  2.0  3.0  NaN
2  4.0  5.0  6.0  NaN
3  7.0  8.0  9.0  NaN
1  0.5  1.0  NaN  1.5
2  2.0  2.5  NaN  3.0
4  3.5  4.0  NaN  4.5

2. Add the underlying numpy objects of the two dataframes, and print the result. (*0.5 points*)

In [14]:
df1.to_numpy() + df2.to_numpy()

array([[ 1.5,  3. ,  4.5],
       [ 6. ,  7.5,  9. ],
       [10.5, 12. , 13.5]])

3. Compare the two results that you obtained and comment if and **why** they are different. (*3 points*)

In [20]:
# Pandas tries to match the rows / columns of each dataframe. 
# If they do not exist in one of the dataframe, the corresponding entry is
# filled with NaNs

print(set(df1.columns.to_list() + df2.columns.to_list()))
print(set(df1.index.to_list() + df2.index.to_list()))

{'a', 'd', 'c', 'b'}
{'2', '4', '3', '1'}


## Other topics

### Broadcasting and vectorized operations:

In class, you've seen how vectorized operations can be much faster than for loops. Example:

In [9]:
big_array = np.zeros(int(1e7))
big_array[1978822] = 1

def _find_element(arr):
    for elem in arr: 
        if elem != 0:
            break

%timeit _find_element(big_array)

160 ms ± 7.41 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [10]:
%timeit np.any(big_array)

10.1 ms ± 118 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Another example. How would you vectorized the following operation of first differences?

In [11]:
a = np.arange(0, 26, 5)
print(a)
diff = np.zeros(a.size - 1)
for i in range(len(a) - 1):
    diff[i] = a[i + 1] - a[i]
print(diff)

[ 0  5 10 15 20 25]
[5. 5. 5. 5. 5.]


In [13]:
# Solution
diff = a[1:] - a[:-1]
print(diff)

[5 5 5 5 5]


This is usually very helpful when you want to optimize operations. Here is an example:

Suppose you have an array of times, *starts*, indicating the starting time of a time block, with a certain duration, *d*. You then have the starting and ending time of other events, *starts_eve*, *ends_eve*. How could you check if the events overlap with at least one of the time blocks and get the corresponding indexes?

In [16]:
# Decrease the sizes for speedup

d = 1
starts = np.concatenate((np.arange(1500, 10000, d), np.arange(20000, 30000, d)))
starts_eve = np.random.rand(5000) * 30000  # 0-1 -> 0-30000
starts_eve = np.sort(starts_eve)
ends_eve = starts_eve + 0.2 * np.maximum(0, np.random.randn(5000)) + 0.1

How would you do it?

In [23]:
# Solution 1

def search_events_1(starts, starts_eve, ends_eve):
    events_list = []
    for i, (start_eve, end_eve) in enumerate(zip(starts_eve, ends_eve)):
        for j, start in enumerate(starts):
            if (start_eve >= start) & (end_eve <= start + d):
                events_list.append((i, j))
    return events_list

%timeit search_events_1(starts, starts_eve, ends_eve)

26 s ± 177 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


However, this method really depends still on the size of the events array! Let's check with a bigger one.

In [24]:
# Solution 2 - eliminate 1 loop

def search_events_2(starts, starts_eve, ends_eve):
    events_list = []
    for i, (start_eve, end_eve) in enumerate(zip(starts_eve, ends_eve)):
        j = np.where((start_eve >= starts) & (end_eve <= starts + d))[0]
        if j.size > 0:
            events_list.append((i, j[0]))
    return events_list

%timeit search_events_2(starts, starts_eve, ends_eve)

167 ms ± 5.38 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [18]:
# Solution 3 - Broadcasting

def search_events_3(starts, starts_eve, ends_eve):

    # Reshape
    starts_ = starts.reshape(-1, 1)  # column vector
    starts_eve_ = starts_eve.reshape(1, -1) # row vector
    ends_eve_ = ends_eve.reshape(1, -1) # row vector
    
    mask_overlap = (starts_eve_ >= starts_) & (ends_eve_ <= starts_ + d)
    
    return mask_overlap

%timeit search_events_3(starts, starts_eve, ends_eve)

158 ms ± 683 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [19]:

mask_overlap = search_events_3(starts, starts_eve, ends_eve)

In [22]:
np.where(mask_overlap)

(array([    1,    10,    22, ..., 18475, 18480, 18491]),
 array([ 252,  254,  256, ..., 4997, 4998, 4999]))

The structure of the output here is a bit different!

### NaNs

When you dataframe contains missing values, you can decide what to do. Pandas has nan-safe functions that (mostly) ignore them. You can also drop them from the dataframe.

In [28]:
dates = pd.date_range("20240308", periods=6)
df2 = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df2 = df2[df2 < 0]
df2

A         B         C         D
2024-03-08 -2.175381 -1.005776 -1.247887 -0.693174
2024-03-09 -0.156496 -0.626008       NaN -0.496904
2024-03-10 -1.743680       NaN       NaN -0.274815
2024-03-11 -0.143888       NaN       NaN -0.260447
2024-03-12       NaN       NaN       NaN       NaN
2024-03-13 -0.565312       NaN -0.083058       NaN

Boolean mask:

In [29]:
pd.isna(df2)

A      B      C      D
2024-03-08  False  False  False  False
2024-03-09  False  False   True  False
2024-03-10  False   True   True  False
2024-03-11  False   True   True  False
2024-03-12   True   True   True   True
2024-03-13  False   True  False   True

Drop nans:

In [30]:
df2.dropna(how="any")

A         B         C         D
2024-03-08 -2.175381 -1.005776 -1.247887 -0.693174

In [31]:
df2.dropna(how="all")

A         B         C         D
2024-03-08 -2.175381 -1.005776 -1.247887 -0.693174
2024-03-09 -0.156496 -0.626008       NaN -0.496904
2024-03-10 -1.743680       NaN       NaN -0.274815
2024-03-11 -0.143888       NaN       NaN -0.260447
2024-03-13 -0.565312       NaN -0.083058       NaN

Fill nans with another value:

In [32]:
df2.fillna(3)

A         B         C         D
2024-03-08 -2.175381 -1.005776 -1.247887 -0.693174
2024-03-09 -0.156496 -0.626008  3.000000 -0.496904
2024-03-10 -1.743680  3.000000  3.000000 -0.274815
2024-03-11 -0.143888  3.000000  3.000000 -0.260447
2024-03-12  3.000000  3.000000  3.000000  3.000000
2024-03-13 -0.565312  3.000000 -0.083058  3.000000

Equivalent to *fillna* is replace:

In [33]:
df2.replace(np.nan, 3)

A         B         C         D
2024-03-08 -2.175381 -1.005776 -1.247887 -0.693174
2024-03-09 -0.156496 -0.626008  3.000000 -0.496904
2024-03-10 -1.743680  3.000000  3.000000 -0.274815
2024-03-11 -0.143888  3.000000  3.000000 -0.260447
2024-03-12  3.000000  3.000000  3.000000  3.000000
2024-03-13 -0.565312  3.000000 -0.083058  3.000000

Another option for replacing could be interpolation, when possible (i.e. with compatible data types)

In [34]:
df2.interpolate()

A         B         C         D
2024-03-08 -2.175381 -1.005776 -1.247887 -0.693174
2024-03-09 -0.156496 -0.626008 -1.014921 -0.496904
2024-03-10 -1.743680 -0.626008 -0.781955 -0.274815
2024-03-11 -0.143888 -0.626008 -0.548990 -0.260447
2024-03-12 -0.354600 -0.626008 -0.316024 -0.260447
2024-03-13 -0.565312 -0.626008 -0.083058 -0.260447

In this case it's linear interpolation. We can check it for a specific entry:

In [35]:
(df2.iloc[1, 0] + df2.iloc[3, 0]) / 2

-0.15019186066640144

In [30]:
?pd.DataFrame.interpolate

Signature:
pd.DataFrame.interpolate(
    self,
    method: 'InterpolateOptions' = 'linear',
    *,
    axis: 'Axis' = 0,
    limit: 'int | None' = None,
    inplace: 'bool_t' = False,
    limit_direction: "Literal['forward', 'backward', 'both'] | None" = None,
    limit_area: "Literal['inside', 'outside'] | None" = None,
    downcast: "Literal['infer'] | None | lib.NoDefault" = <no_default>,
    **kwargs,
) -> 'Self | None'
Docstring:
Fill NaN values using an interpolation method.

Please note that only ``method='linear'`` is supported for
DataFrame/Series with a MultiIndex.

Parameters
----------
method : str, default 'linear'
    Interpolation technique to use. One of:

    * 'linear': Ignore the index and treat the values as equally
      spaced. This is the only method supported on MultiIndexes.
    * 'time': Works on daily and higher resolution data to interpolate
      given length of interval.
    * 'index', 'values': use the actual numerical values of the index.
    * 'pad': Fi

In [36]:
df2.interpolate("spline", order=1)

A         B         C         D
2024-03-08 -2.175381 -1.005776 -1.247887 -0.693174
2024-03-09 -0.156496 -0.626008 -1.014921 -0.496904
2024-03-10 -1.743680 -0.246240 -0.781955 -0.274815
2024-03-11 -0.143888  0.133528 -0.548990 -0.260447
2024-03-12 -0.516148  0.513296 -0.316024 -0.051268
2024-03-13 -0.565312  0.893064 -0.083058  0.100759

nan-safe operations:

In [37]:
?pd.DataFrame.mean

Signature:
pd.DataFrame.mean(
    self,
    axis: 'Axis | None' = 0,
    skipna: 'bool' = True,
    numeric_only: 'bool' = False,
    **kwargs,
)
Docstring:
Return the mean of the values over the requested axis.

Parameters
----------
axis : {index (0), columns (1)}
    Axis for the function to be applied on.
    For `Series` this parameter is unused and defaults to 0.

    For DataFrames, specifying ``axis=None`` will apply the aggregation
    across both axes.

    .. versionadded:: 2.0.0

skipna : bool, default True
    Exclude NA/null values when computing the result.
numeric_only : bool, default False
    Include only float, int, boolean columns. Not implemented for Series.

**kwargs
    Additional keyword arguments to be passed to the function.

Returns
-------
Series or scalar

            Examples
            --------
            >>> s = pd.Series([1, 2, 3])
            >>> s.mean()
            2.0

            With a DataFrame

            >>> df = pd.DataFrame({'a': [1, 2], '

In [38]:
df2.mean(skipna=True)

A   -0.956951
B   -0.815892
C   -0.665473
D   -0.431335
dtype: float64

In [39]:
df2.mean(skipna=False)

A   NaN
B   NaN
C   NaN
D   NaN
dtype: float64

In [41]:
np.nanmean(df2.to_numpy(), axis=0)

array([-0.95695147, -0.81589173, -0.6654726 , -0.43133496])